git:
  depth: 1
language: node_js
node_js:
- 5
cache:
  directories:
  - node_modules
before_script:
- npm install -g npm
- npm install -g gulp-cli
- npm install -g casperjs
- npm install -g phantomjs
- chmod +x ./deploy-website.sh
script: "./deploy-website.sh"
